sudo: false

language: node_js

node_js:
  - 8

before_script:
  - npm install -g jest commitizen
  
script:
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
